### ISSUE TITLE
Can only select one letter

### ISSUE THREAD

**Issue by dandv** [PolymerElements/iron-doc-viewer#40] opened 2015-05-29 08:18 UTC
I can't select more than one letter of text using the mouse in doc pages like https://elements.polymer-project.org/elements/paper-material

![can t select text in the documentation](https://cloud.githubusercontent.com/assets/33569/7878966/a40a4ac0-05a0-11e5-9e1e-4b90cb9edce8.gif)

**Comment by notwaldorf** [comment] 2015-06-19 20:43
I can select this in today's version, so probably something was already fixed? Please re-open if it's still a problem. Thanks!

**Comment by dandv** [comment] 2015-06-19 22:27
The bug is still there: double-click selects the whole world, but pressing the mouse button and dragging doesn't extend the selection.

Chrome 43.0.2357.124 m on Windows 7.

**Comment by notwaldorf** [comment] 2015-06-19 22:58
Huh, that's so weird. `paper-material` doesn't work, but the `paper-input` page does: https://elements.polymer-project.org/elements/paper-input. Looking into it.

**Comment by notwaldorf** [comment] 2015-06-19 23:44
Ah, this is a duplicate of https://github.com/PolymerElements/paper-drawer-panel/issues/50, which means it should be fixed in the next catalog push. Re-closing.

**Closed as completed by notwaldorf** 2015-06-19 23:44 UTC
Labels: bug, duplicate
